sudo: required
services:
  - docker

before_install:
  docker build -t evelynvieira/docker-react-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true evelynvieira/docker-react-sample npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-sample"
  env: "DockerReactSample-env"
  bucket_name: "elasticbeanstalk-eu-west-1-012653156112"
  bucket_path: "docker-react-sample"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  


   